const SAP_MAPS = {
  ProjectType: {
    "Single Project (Do not use)": "102",
    "Single project": "25",
    "Cont. collab. project": "Z01",
    "Grant project (EU-FP, etc.)": "Z02",
    "Referral (only to invoice)": "Z04",
  },
  Source: {
    "Evento/feria (indicar en el campo campaña)": "001",
    "Campaña (indicar en el campo campaña)": "003",
    "Lead digital": "004",
    "Plataforma de reuniones en línea": "005",
    "Knowledge Center": "101",
    "EU Reference": "102",
    "Socio comercial/Referral (indicar partes implicadas)": "Z01",
    "Referencia de otro cliente (especificar cliente)": "Z02",
    "Red personal": "Z03",
    Farming: "Z05",
    "Recomendación externa": "Z01",
  },
  TechnicalUnit: {
    "eSub RegOps": "Z001",
    "DATA RegOps": "Z002",
    CMC: "Z003",
    DW: "Z004",
    MedTech: "Z005",
    LCM: "Z006",
    PV: "Z007",
    "European Projects": "Z008",
    Transversal: "Z009",
    "Business Development": "Z010",
    Others: "Z011",
  },
  Category: {
    "eSub RegOps": "Z001",
    "DATA RegOps": "Z002",
    CMC: "Z003",
    DW: "Z004",
    MedTech: "Z005",
    LCM: "Z006",
    PV: "Z007",
    "European Projects": "Z008",
    Transversal: "Z009",
    "Business Development": "Z010",
    Others: "Z011",
  },
  TherapeuticalArea: {
    "A - Alimentary tract and metabolism": "136",
    "B - Blood and blood forming organs": "137",
    "C - Cardiovascular system": "138",
    "D - Dermatologicals": "139",
    "G - Genito-urinary system and sex hormones": "140",
    "H - Systemic hormonal preparations, excluding sex hormones and insulins": "141",
    "J - Antiinfectives for systemic use": "142",
    "L - Antineoplastic and immunomodulating agents": "143",
    "M - Musculo-skeletal system": "144",
    "N - Nervous system": "145",
    "P - Antiparasitic products, insecticides and repellents": "146",
    "R - Respiratory system": "147",
    "S - Sensory organs": "148",
    "V - Various (allergens, diagnostic agents, etc.)": "149",
    "Others (if the product is not a drug)": "150",
    "Not applicable (when there is not product)": "151",
  },
  LegalBasis: {
    "Full dossier (8(3), NDA505(b)(1), BLA351(a), NDS, etc.)": "153",
    "WEU (10(a))": "154",
    "Fixed Dose Combination (10(b), etc.)": "155",
    "Generic (10(1), ANDA, ANDS, etc.)": "156",
    "Hybrid / Mixed / Modified / etc. (10(3), NDA505(b)(2), etc.)": "157",
    "Biosimilar (10(4), BLA 351(k), etc.)": "158",
    "Medical Device certification / registration (EU DIR / MDR, 510(k), etc.)": "159",
    Others: "160",
    "Not applicable (NA)": "161",
    "To be defined (TBD)": "162",
  },
  Procedure: {
    "EMA/FDA procedure during development (excluding meetings/SA/pre-IND, etc.)": "164",
    "Agency meeting (SA, pre-IND, pre-submission, etc.)": "165",
    "Clinical Trial Application (CTA) / Investigational New Drug (IND)": "166",
    "Orphan Drug Designation (ODD)": "167",
    "Paediatric Investigation Plan (PIP) / PSP / WR / BPCA / etc.": "168",
    "EMA Centralised Procedure (CP)": "169",
    "EU Decentralised Procedure (DCP) / Mutual Recognition Pr. (MRP) / Repeat Use Pr. (RUP)": "170",
    "National Marketing Authorization Application (NP, MAA, NDA/BLA, NDS, etc.)": "171",
    "Active Substance Master File (ASMF) / Drug Master File (DMF)": "172",
    "Certi. Suitab. to monographs European Pharmacopoeia (CEP)": "173",
    "Medical Device certification / notification": "174",
    "Pricing and Reimbursement (P&R)": "175",
    "Small and Medium-sized Enterprises (SME) application": "176",
    Others: "177",
    "Not applicable (NA)": "178",
    "Development projects": "179",
    "Local Contact": "180",
  },
  HuntingFarming: {
    Hunting: "131",
    Farming: "132",
    "Cross Selling": "133",
  },
  PaymentTerms: {
    "120 days net": "ZC01",
    "30 days net": "1003",
    "30 days net, fixed day 15": "ZC09",
    "30 days net, fixed day 20": "ZC08",
    "30 days net, fixed day 25": "ZC10",
    "30 days net, fixed day 26": "ZC05",
    "30 days net, fixed day 30": "ZC07",
    "40 days net": "ZC02",
    "45 days net": "1004",
    "45 days net, fixed day 5": "ZC11",
    "60 days net": "1005",
    "60 days net, fixed day 25": "ZC06",
    "60 days net, fixed day 30": "ZC12",
    "75 days net": "ZC03",
    "90 days net": "ZC04",
    "Payable immediately due net": "1001",
  },
  Probability: {
    "0%": "103",
    "25%": "104",
    "50%": "105",
    "75%": "106",
    "100%": "107",
  },
  TypeOfProduct: {
    "Not applicable (NA)": "102",
    "To be defined (TBD)": "103",
    "SMD NCEs/NMEs": "104",
    "SMD Known molecules": "105",
    "SMD APIs only": "106",
    "SMD Medicinal gases": "107",
    "SMD Fixed dose combinations": "108",
    "SMD Others": "109",
    "BIO Peptides and small proteins": "110",
    "BIO Large proteins, antibodies, fusion proteins": "111",
    "BIO Vaccines, immuno-therapeutic products": "112",
    "BIO ATMP cell therapies": "113",
    "BIO ATMP gene therapies": "114",
    "BIO ATMP tissue engineered products": "115",
    "BIO ATMP combination product": "116",
    "BIO Others": "117",
    "MD Biomarkers/IVDs": "118",
    "MD Borderline products": "119",
    "MD Device of combination product": "120",
    "MD Electromechanics": "121",
    "MD Materials and biomaterials": "122",
    "MD Software": "123",
    "MD Substance-based": "124",
    "MD Others": "125",
    "Combination products others": "126",
    "Complex molecules (not biologicals)": "127",
    "Nanomedicines": "128",
    "Herbal medicinal products": "129",
    "Cosmetics": "130",
    "Food supplements": "131",
    "Software (eCTD, PhV, RIM, etc.)": "132",
    "Veterinary products": "133",
    "Others": "134"
  },
  PricingType: {
    "Fixed": "PBFP",
    "T&M": "PBTM"
  }
};

module.exports = SAP_MAPS;
